Class {
	#name : #GRMockSession,
	#superclass : #Object,
	#category : #'GReaSe-Test'
}

{ #category : #'as yet unclassified' }
GRMockSession >> callOn: anObject method: aSymbol arguments: aCollection [

	
]

{ #category : #'as yet unclassified' }
GRMockSession >> get: aSymbol of: anObject [

	
]

{ #category : #'as yet unclassified' }
GRMockSession >> set: aSymbol of: anObject to: anotherObject [

	
]
