Class {
	#name : #CodeBlockLayoutParamters,
	#superclass : #Object,
	#instVars : [
		'blockDepth',
		'morphicScale'
	],
	#category : #'Dworphic-BlockCode'
}

{ #category : #'as yet unclassified' }
CodeBlockLayoutParamters >> blockDepth [

	^ blockDepth
]

{ #category : #'as yet unclassified' }
CodeBlockLayoutParamters >> blockDepth: aNumber [

	blockDepth := aNumber
]

{ #category : #'as yet unclassified' }
CodeBlockLayoutParamters >> morphicScale [

	^ morphicScale
]

{ #category : #'as yet unclassified' }
CodeBlockLayoutParamters >> morphicScale: aNumber [

	morphicScale := aNumber
]
